name: Test Node.js ES module exports

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]
        node: [
          lts/*,   # Original CI configuration
          20.8.1,  # Latest at https://github.com/actions/node-versions/releases
          18.18.2, # LTS at https://nodejs.org/
          12.22.12 # Debian 11
        ]
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
          - name: macos
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Test
      run: npm run dev
